name: deploy-ml-model-in-aws

services:
  terraform:
    build: .
    image: deploy-ml-model-in-aws:dev
    container_name: deploy-ml-model-in-aws
    env_file:
      - .env
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
